default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-added-large-files
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.17"
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: "v0.0.50"
    hooks:
      - id: ty
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v4.4.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
