[tool.poetry]
name = "wemod-launcher"
version = "0.1.0"
description = ""
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
