name: Bug report
description: Create a bug report to help us improve
title: '[BUG]: The Wemod Launcher fails to (fill in)'
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the issue you encountered.
      placeholder: I was trying to [...]
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: List the exact steps to reproduce the issue.
      placeholder: |
        1. Go to [...]
        2. Press [...]
        3. Observe the error [...]
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
      placeholder: I expected [...]
    validations:
      required: true

  - type: textarea
    id: any-logs
    attributes:
      label: Logs or Terminal Output
      description: |
        Please provide logs to help us understand the issue.

        - Preferred: Upload your `wemod.log` file.
        - If unavailable:
          - If using **Steam**, provide the terminal output from the `steam` command.
          - If using **Lutris** or another launcher, provide that launcher's output.
      placeholder: |
        - Drag and drop `wemod.log` here.
        - If not available, paste the terminal output (e.g., from Steam or Lutris).
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your issue.
      placeholder: Drag and drop screenshots here.
    validations:
      required: false

  - type: textarea
    id: system-information
    attributes:
      label: System Information
      description: Please provide system details for better debugging.
      placeholder: |
        * OS: [e.g. Arch Linux 2024.06.01]
        * Wine/Proton Version: [e.g. Proton GE 9.3]
        * Launcher: [e.g. Lutris, Steam, Heroic]
        * Window Manager / Session: [e.g. KDE over Wayland, Gnome over X11]
        * GPU Vendor: [e.g. Nvidia, AMD, Intel]
        * Launcher running under: [e.g. System binaries (native), Flatpak (sandboxed), AppImage]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Include any other relevant details or configuration quirks.
      placeholder: Add any extra context about the problem here.
    validations:
      required: false
