name: Question
description: Ask a question about the project
title: '[Question] How do I use the wemod-laucher for x'
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Your question about the project.
      placeholder: Describe your question in detail.
    validations:
      required: true

  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: Provide details about your environment.
      placeholder: |
        * OS: [e.g. Arch Linux 2024.06.01]
        * Wine/Proton Version: [e.g. Proton GE 9.3]
        * Launcher: [e.g. Lutris, Steam, Heroic]
        * Window Manager / Session: [e.g. KDE over Wayland, Gnome over X11]
        * GPU Vendor: [e.g. Nvidia, AMD, Intel]
        * Launcher running under: [e.g. System binaries (native), Flatpak (sandboxed), AppImage]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional context or information that might help answer your question.
      placeholder: Provide any other relevant details here.
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs (if applicable)
      description: Optional log section for additional context.
      placeholder: Paste log output here if relevant to your question.
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information or things related to your question.
      placeholder: Add any other relevant information or related things here.
    validations:
      required: false
