name: Run linter on codebase and commits in PRs

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  run-prek-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: j178/prek-action@v2
